#!/bin/bash
source ~/.bashrc
export FREDNORTH_DB_USERNAME=$(cat resources/environment/username)
export FREDNORTH_DB_PASSWORD=$(cat resources/environment/password)
export NODE_ENV=$(cat resources/environment/environment)
export DATABASE=$(cat resources/environment/database)
export SERVICE_PORT=$(cat resources/environment/servicePort)
export SITE_PORT=$(cat resources/environment/sitePort)
export GOOGLE_CLIENT_SECRET=$(cat resources/environment/googleClientSecret)
export GOOGLE_CLIENT_ID=$(cat resources/environment/googleClientId)
export REALM=$(cat resources/environment/realm)
pwd=$(pwd)
case $1 in
"START")
        npm install
        forever start $pwd/site.js
	;;
"SITE")
        npm install
        node $pwd/site.js
	;;
"SYNC")
        git fetch
	if [ "$#" -ne 2 ]
	then
	  echo "Usage ./application SYNC git_branch"
	  exit 1
	fi
	git checkout $2
	git pull
        ;;
"STOP")	
        forever stop $pwd/site.js
	;;
esac
